# Generated by Django 6.0.2 on 2026-03-04 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20, verbose_name="mês")),
                (
                    "start_sale_period",
                    models.DateField(verbose_name="inicio do periodo de venda"),
                ),
                (
                    "end_sale_period",
                    models.DateField(verbose_name="fim do periodo de venda"),
                ),
                ("order_number", models.IntegerField(verbose_name="numero da ordem")),
                (
                    "order_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor da ordem"
                    ),
                ),
                (
                    "value_sold",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor vendido"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=30, verbose_name="nome do produto"),
                ),
                ("product_code", models.IntegerField(verbose_name="código do produto")),
                (
                    "product_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor do produto"
                    ),
                ),
                ("product_quantity", models.IntegerField(verbose_name="quantidade")),
                (
                    "quantity_sold",
                    models.IntegerField(verbose_name="quantidade vendida"),
                ),
                (
                    "product_briefcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.maleta",
                        verbose_name="maleta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor da venda"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=20, verbose_name="método de pagamento"),
                ),
                (
                    "installments",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantidade de parcelas",
                    ),
                ),
                (
                    "in_good_standing",
                    models.BooleanField(
                        default=True, verbose_name="situação de pagamento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data da venda"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualização"),
                ),
                (
                    "briefcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.maleta",
                        verbose_name="maleta",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.clientes",
                        verbose_name="cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItensVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço unitario"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.produtos",
                        verbose_name="produto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="sales.vendas",
                        verbose_name="venda",
                    ),
                ),
            ],
        ),
    ]
