# Generated by Django 6.0.2 on 2026-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="in_good_standing",
            field=models.CharField(
                choices=[
                    ("Adimplente", "Adimplente"),
                    ("inadimplente", "Inadimplente"),
                ],
                max_length=20,
                verbose_name="situação de pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Pix", "Pix"),
                    ("Débito", "Debito"),
                    ("Crédito", "Credito"),
                    ("Dinheiro", "Dinheiro"),
                ],
                max_length=20,
                verbose_name="método de pagamento",
            ),
        ),
    ]
