# Generated by Django 6.0.2 on 2026-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_vendas_in_good_standing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itensvenda",
            options={
                "verbose_name": "itens venda",
                "verbose_name_plural": "itens vendas",
            },
        ),
        migrations.AlterModelOptions(
            name="maleta",
            options={"verbose_name": "maleta", "verbose_name_plural": "maletas"},
        ),
        migrations.AlterModelOptions(
            name="produtos",
            options={"verbose_name": "produto", "verbose_name_plural": "produtos"},
        ),
        migrations.AlterModelOptions(
            name="vendas",
            options={"verbose_name": "venda", "verbose_name_plural": "vendas"},
        ),
    ]
