# Generated by Django 6.0.2 on 2026-03-13 17:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_itensvenda_options_alter_maleta_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itensvenda",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="itensvenda",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="preço unitario",
            ),
        ),
        migrations.AlterField(
            model_name="maleta",
            name="month",
            field=models.CharField(
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                verbose_name="mês",
            ),
        ),
        migrations.AlterField(
            model_name="maleta",
            name="order_number",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="numero da ordem"
            ),
        ),
        migrations.AlterField(
            model_name="maleta",
            name="order_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor da ordem",
            ),
        ),
        migrations.AlterField(
            model_name="maleta",
            name="value_sold",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor vendido",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="product_code",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="código do produto"
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="product_quantity",
            field=models.PositiveIntegerField(verbose_name="quantidade"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="product_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor do produto",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="quantity_sold",
            field=models.PositiveIntegerField(verbose_name="quantidade vendida"),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="installments",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantidade de parcelas",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="sale_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor da venda",
            ),
        ),
    ]
