# Generated by Django 6.0.2 on 2026-03-23 16:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_itensvenda_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itensvenda",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Desconto em Porcentagem.",
            ),
        ),
        migrations.AddField(
            model_name="itensvenda",
            name="integer_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Desconto em Porcentagem.",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="installments",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="quantidade de parcelas",
            ),
        ),
    ]
