# Generated by Django 6.0.2 on 2026-03-23 18:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_itensvenda_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendas",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="desconto",
            ),
        ),
        migrations.AddField(
            model_name="vendas",
            name="end_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor final da venda",
            ),
        ),
        migrations.AddField(
            model_name="vendas",
            name="sale_itens",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.itensvenda",
                verbose_name="itens na venda",
            ),
        ),
        migrations.AlterField(
            model_name="itensvenda",
            name="integer_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Desconto em Dinheiro.",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="sale_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor integro da venda",
            ),
        ),
    ]
