# Generated by Django 6.0.2 on 2026-03-23 18:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_vendas_discount_vendas_end_value_vendas_sale_itens_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendas",
            name="sale_itens",
        ),
        migrations.AlterField(
            model_name="vendas",
            name="sale_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor integro da venda",
            ),
        ),
    ]
