# Generated by Django 6.0.2 on 2026-03-26 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_remove_vendas_sale_itens_alter_vendas_sale_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maleta",
            name="value_sold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor vendido",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="briefcase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendas",
                to="sales.maleta",
                verbose_name="maleta",
            ),
        ),
    ]
