# Generated by Django 6.0.2 on 2026-03-26 15:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_maleta_value_sold_alter_vendas_briefcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itensvenda",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="preço unitario",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="quantity_sold",
            field=models.PositiveIntegerField(
                default=0, verbose_name="quantidade vendida"
            ),
        ),
    ]
