# Generated by Django 6.0.2 on 2026-03-26 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_alter_itensvenda_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="sale_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor integro da venda",
            ),
        ),
    ]
