# Generated by Django 6.0.2 on 2026-04-18 18:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_alter_vendas_sale_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="desconto",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="end_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor final da venda",
            ),
        ),
    ]
