# Generated by Django 6.0.2 on 2026-04-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_alter_vendas_discount_alter_vendas_end_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itensvenda",
            unique_together={("sale", "product")},
        ),
    ]
