# Generated by Django 6.0.2 on 2026-05-02 13:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_imutabilidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itensvenda",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Desconto em Porcentagem.",
            ),
        ),
        migrations.AlterField(
            model_name="maleta",
            name="month",
            field=models.CharField(
                choices=[
                    ("janeiro", "Janeiro"),
                    ("fevereiro", "Fevereiro"),
                    ("março", "Março"),
                    ("abril", "Abril"),
                    ("maio", "Maio"),
                    ("junho", "Junho"),
                    ("julho", "Julho"),
                    ("agosto", "Agosto"),
                    ("setembro", "Setembro"),
                    ("outubro", "Outubro"),
                    ("novembro", "Novembro"),
                    ("dezembro", "Dezembro"),
                ],
                max_length=20,
                verbose_name="mês",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="product_code",
            field=models.PositiveIntegerField(verbose_name="código do produto"),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="in_good_standing",
            field=models.CharField(
                choices=[
                    ("adimplente", "Adimplente"),
                    ("inadimplente", "Inadimplente"),
                ],
                max_length=20,
                verbose_name="situação de pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("pix", "Pix"),
                    ("debito", "Débito"),
                    ("credito", "Crédito"),
                    ("dinheiro", "Dinheiro"),
                ],
                max_length=20,
                verbose_name="método de pagamento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="produtos",
            unique_together={("product_briefcase", "product_code")},
        ),
    ]
