# Generated by Django 6.0.2 on 2026-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="primeiro nome"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="sobrenome"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="número de telefone"),
                ),
            ],
        ),
    ]
