# Generated by Django 6.0.2 on 2026-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("sales", "0003_alter_itensvenda_options_alter_maleta_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clientes",
            new_name="Cliente",
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "cliente", "verbose_name_plural": "clientes"},
        ),
    ]
