# Generated by Django 6.0.2 on 2026-03-12 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_rename_clientes_cliente_alter_cliente_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="first_name",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um nome válido.", regex="^[a-zA-Z]+$"
                    )
                ],
                verbose_name="primeiro nome",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um nome válido.", regex="^[a-zA-Z]+$"
                    )
                ],
                verbose_name="sobrenome",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um número de telefone válido.",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="número de telefone",
            ),
        ),
    ]
