# Generated by Django 6.0.2 on 2026-05-02 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_cliente_first_name_alter_cliente_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="first_name",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um nome válido.", regex="^[a-zA-ZÀ-ÿ]+$"
                    )
                ],
                verbose_name="primeiro nome",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um nome válido.", regex="^[a-zA-ZÀ-ÿ]+$"
                    )
                ],
                verbose_name="sobrenome",
            ),
        ),
    ]
